### ISSUE TITLE
trust relationship error

### ISSUE THREAD

**Issue by tprzyzycki** [tfenster/dockeraccesshelper#5]
PS C:\WINDOWS\system32> Add-AccountToDockerAccess "myusername"
Exception calling "AddAccessRule" with "1" argument(s): "The trust relationship between this workstation and the primary domain failed.
"
At C:\Program Files\WindowsPowerShell\Modules\dockeraccesshelper\0.0.3\Add-AccountToDockerAccess.psm1:67 char:5
+     $dSec.AddAccessRule($rule)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SystemException

**Comment by tfenster** [comment]
@tprzyzycki This happens in my experience if a) you've been disconnected from the domain controller for too long or b) the password you use locally and the password that is stored on the directory are out of sync. Does everything else work for you?

**Comment by tprzyzycki** [comment]
I managed to get it working.  Thanks for your suggestions
