### ISSUE TITLE
The file is not digitally signed

### ISSUE THREAD

**Issue by Saibamen** [tfenster/dockeraccesshelper#6]
```
PS C:\WINDOWS\system32> Import-Module dockeraccesshelper

Import-Module : File C:\Program
Files\WindowsPowerShell\Modules\dockeraccesshelper\0.0.3\Add-AccountToDockerAccess.psm1 cannot be loaded. The file
C:\Program Files\WindowsPowerShell\Modules\dockeraccesshelper\0.0.3\Add-AccountToDockerAccess.psm1 is not digitally
signed. You cannot run this script on the current system. For more information about running scripts and setting
execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ Import-Module dockeraccesshelper
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [Import-Module], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by tfenster** [comment]
@Saibamen Thanks for opening this issue, but I don't plan to sign the module. You can change the execution policy as explained here https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-5.1 as a workaround

**Comment by Saibamen** [comment]
Doesn't matter for me anymore, because Azure Virtual Machines doesn't support virtualization...

**Comment by tfenster** [comment]
@Saibamen you mean nested virtualization? If yes, then it depends on the machine type. I don't remember the full list, but we are mostly using Dv3/4 and Ev3/4 and those support nested virt
